repos:
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        language_version: python3.8
        exclude: |
          (?x)^(
              versioneer.py|
              docs/conf.py|
              lpsd/_version.py
          )$
